kind: pipeline
name: default
type: docker

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: USERNAME
    password:
      from_secret: PASSWORD
    repo: git.local.guluarte.com/guluarte/jobflow/jobflow-app
    tags:
    - latest
    DOPPLER_TOKEN:
      from_secret: DOPPLER_TOKEN