services:
  app:
    restart: unless-stopped
    image: git.local.guluarte.com/guluarte/jobflow/jobflow-app:latest
    ports:
      - 3000:3000
  directus:
    image: directus/directus:10.7.2
    restart: unless-stopped
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    environment:
      KEY: "5z1DSfIXyyOW5cEu5LlYiaA9e7uzFHUpFj+vJMfmr14="
      SECRET: "HLhncn/EciE/hlAn3XSKBCUurmhsQc7i4On04OSLQvc="
      ADMIN_EMAIL: "${DIRECTUS_ADMIN}"
      ADMIN_PASSWORD: "${DIRECTUS_ADMIN_PASSWORD}"
      DB_CLIENT: "mysql"
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      WEBSOCKETS_ENABLED: true
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://redis:6379"
    depends_on:
      - mysql
      - redis
    networks:
      - jobflow
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - jobflow
  redis:
    restart: unless-stopped
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - jobflow
    volumes:
      - ./database/redis:/data

networks:
  jobflow:
    driver: bridge
