version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./wp-data:/var/www/html
      - ./wordpres.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DEBUG: 0
      WORDPRESS_DB_HOST: "${DB_HOST}:3306"
      WORDPRESS_DB_USER: "${DB_USERNAME}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_DATABASE}"
    networks:
      - jobflow

  directus:
    restart: unless-stopped
    image: directus/directus:10.7.2
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    environment:
      KEY: "5z1DSfIXyyOW5cEu5LlYiaA9e7uzFHUpFj+vJMfmr14="
      SECRET: "HLhncn/EciE/hlAn3XSKBCUurmhsQc7i4On04OSLQvc="
      ADMIN_EMAIL: "${DIRECTUS_ADMIN}"
      ADMIN_PASSWORD: "${DIRECTUS_ADMIN_PASSWORD}"
      DB_CLIENT: "mysql"
      DB_HOST: "${DB_HOST}"
      DB_PORT: 3306
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      WEBSOCKETS_ENABLED: true
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://redis:6379"
    depends_on:
      - mysql
      - redis
    networks:
      - jobflow

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - jobflow

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - jobflow
    volumes:
      - ./database/redis:/data

networks:
  jobflow:
    driver: bridge
