stages:
  - build
  - test

build:
  image: alpine:latest
  steps:
    - name: Checkout code
      checkout: self

    - name: Install dependencies
      run: |
        wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub &&
        echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories &&
        apk add doppler

test:
  image: alpine:latest
  steps:
    - name: Run tests
      run: |
        npm run build && npm start
