version: "3"
services:
  jobflow-directus:
    image: directus/directus:10.7.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: "5z1DSfIXyyOW5cEu5LlYiaA9e7uzFHUpFj+vJMfmr14="
      SECRET: "HLhncn/EciE/hlAn3XSKBCUurmhsQc7i4On04OSLQvc="
      ADMIN_EMAIL: "rodo@guluarte.com"
      ADMIN_PASSWORD: "Npa7hWwDZuf69Q"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
