# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint CI

on:
  push:
    branches: ["test", "main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install CLI
        uses: dopplerhq/cli-action@v2
      - name: Use Node.js 20.5.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0
          cache: "npm"
      - run: npm ci
      - run: npm run lint
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
